export const basic = [
  ["😀", "grinning 웃음"],
  ["😄", "smile 미소"],
  ["😆", "laugh 웃음"],
  ["😅", "sweat 식은땀"],
  ["😂", "joy 눈물 웃음"],
  ["🙂", "slight smile 미소"],
  ["😉", "wink 윙크"],
  ["😊", "blush 미소"],
  ["😍", "heart eyes 사랑"],
  ["🥰", "love 사랑"],
  ["😎", "cool 멋짐"],
  ["🤔", "thinking 생각"],
  ["😴", "sleep 잠"],
  ["😭", "cry 울음"],
  ["😡", "angry 화남"],
  ["🥳", "party 파티"],
  ["👍", "thumbsup 좋아"],
  ["👎", "thumbsdown 싫어"],
  ["👏", "clap 박수"],
  ["🙏", "pray 감사"],
  ["💪", "muscle 힘"],
  ["❤️", "heart 하트"],
  ["✨", "sparkles 반짝"],
  ["🎉", "tada 축하"]
];
