include /etc/nginx/modules-enabled/*.conf;
user www-data;
worker_processes 1;
pid /run/oanismajor-storage.pid;
error_log stderr warn;
events { worker_connections 1024; }
stream {
    server {
        listen __ADDRESS__:2049;
        allow __NETWORK__;
        deny all;
        proxy_pass __UPSTREAM__;
        proxy_connect_timeout 3s;
        proxy_timeout 1d;
    }
}
